# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 250)
        Form.setMaximumSize(QtCore.QSize(400, 250))
        self.OkayButton_Welcome = QtWidgets.QPushButton(Form)
        self.OkayButton_Welcome.setGeometry(QtCore.QRect(100, 180, 75, 23))
        self.OkayButton_Welcome.setObjectName("OkayButton_Welcome")
        self.CancelButton_Welcome = QtWidgets.QPushButton(Form)
        self.CancelButton_Welcome.setGeometry(QtCore.QRect(225, 180, 75, 23))
        self.CancelButton_Welcome.setObjectName("CancelButton_Welcome")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(155, 40, 90, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(75, 80, 250, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.OkayButton_Welcome.setText(_translate("Form", "Okay"))
        self.CancelButton_Welcome.setText(_translate("Form", "Cancel"))
        self.label.setText(_translate("Form", "Welcome!"))
        self.label_2.setText(_translate("Form", "Please make sure your face is not obstructed, then press the \"Okay\" button."))
